### ISSUE TITLE
My schedule: duplicate sessions

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#88] opened 2018-06-07 18:20 UTC
When you favorite a session that is happening in multiple tracks/workshops (like the one of Matt at 14:00), you will get it 5 times in 'My schedule'

**Comment by luisherranz** [comment] 2018-06-07 18:23
Duplicate of https://github.com/frontity/wordcamp-theme/issues/82#event-1669064689

**Closed as completed** 2018-06-07 18:23 UTC
