### ISSUE TITLE
Link in announcement pop-up not working 

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#64] opened 2018-05-30 12:45 UTC
On my Android phone I have activated the 'Push Notifications' and I received the 'subscribed' message.

I have just published an announcement (Contributor Day Details) and received the pop-up. When clicking on that pop-up it tries to open https://app.wp-europe.org/contributor-day-details/ and that does not seem to work.

(Has to see with redirection or something else ??? Just guessing)

**Comment by luisherranz** [comment] 2018-05-30 13:40
Duplicate of https://github.com/frontity/wordcamp-theme/issues/61.

It's already solved, but not on production yet. Probably tomorrow.

**Closed as completed by luisherranz** 2018-05-30 13:40 UTC
Labels: bug, duplicate, deployed
