### ISSUE TITLE
Unable to start the app from home screen

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#74] opened 2018-05-31 12:31 UTC
I opened the app in the Samsung browser (I do not have Chrome on my S5) and did the 'Add the home screen'. It created the icon.

When I now click on the icon, it opens a white screen with the WCEU logo and in full below 'WordCamp Europe 2018', but then nothing else happens.

**Comment by luisherranz** [comment] 2018-05-31 14:27
Could you please visit http://www.whatsmyua.info/ and paste your User Agent here?

**Comment by ePascalC** [comment] 2018-05-31 15:45
Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G901F Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36

**Comment by luisherranz** [comment] 2018-06-01 09:40
Thanks @ePascalC. We'll take a look with the Android emulator.

**Comment by luisherranz** [comment] 2018-06-01 10:07
I can't reproduce the problem with an Android 6.0 and Chrome 56.0.2924.87.

Could you please connect your phone via USB, visit chrome://inspect and open the inspector to look for JS error? If you don't know how to do that let me know and I'll guide you through.

**Comment by ePascalC** [comment] 2018-06-05 13:00
@luisherranz As I indicated above: `I opened the app in the Samsung browser (I do not have Chrome on my S5)` so the problem is probably only for people that do not use Chrome.

**Comment by ePascalC** [comment] 2018-06-05 13:01
Please focus on other issues, because this will probably only be an edge case.

**Comment by luisherranz** [comment] 2018-06-08 14:35
Closing this now. Please feel free to reopening it when you can debug it using the inspector.

**Closed as completed by luisherranz** 2018-06-08 14:35 UTC
Labels: bug, dev-team, blocked

**Comment by ePascalC** [comment] 2018-06-08 14:44
@luisherranz I'm ok for the closure now, but 'Inspector' is a Chrome thing. I cannot simulate/inspect anything from the built in browser (that is not Chrome).

**Comment by luisherranz** [comment] 2018-06-08 15:50
According to your `UserAgent` it is a Chrome 56. Not sure if Samsung allows to connect it via chrome://inspect tho.
