### ISSUE TITLE
Link to venue map

### ISSUE THREAD

**Issue by mburridge** [frontity/wordcamp-theme#71] opened 2018-05-31 10:31 UTC
When you click on a talk/workshop and view the details the speaker is clickable and takes you to the speaker profile. Can we make the venue clickable too so that you're taken to the appropriate map?

**Comment by luisherranz** [comment] 2018-05-31 10:41
We've just published a new version which includes this!

(duplicate of https://github.com/frontity/wordcamp-theme/issues/66)

**Comment by mburridge** [comment] 2018-05-31 16:27
I'm not seeing this, the track on the talk details page is not clickable, only the speaker.

**Comment by luisherranz** [comment] 2018-05-31 18:17
Oh, I thought you were talking about the "On now" and "Up next" screens, sorry. We'll add the link there as well, no problem 👍

**Comment by mburridge** [comment] 2018-06-01 16:31
Track in talk/workshop details still not a link, so re-opening. Let me know if you're not going to do this. Thanks.

**Comment by luisherranz** [comment] 2018-06-01 16:46
@mburridge this is solved in this commit https://github.com/frontity/wordcamp-theme/commit/ac64345581f0e19db5d3e178db10c15a0750b8e5, but not in production yet.


We use waffle.io to move issues between columns and this one is now in our `ready-to-deploy` column. Once it's on production we'll move it to the `deployed` column. Maybe we should add GitHub tags for `ready-to-deploy` column as well. We only have for `next`, `in-progress` and `deployed`.

By the way, we will publish a new version next Monday morning.

**Closed as completed by luisherranz** 2018-06-01 16:46 UTC
Labels: enhancement, nice-to-have, deployed
